name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 217.199.253.41
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: PORT,NODE_ENV
          script: |
            set -e
            cd /opt/back/GENOM
            echo ">>> Fetching latest code"
            git fetch --all
            git reset --hard origin/main

            echo ">>> Pulling latest Docker images"
            docker compose pull

            echo ">>> Stopping existing containers"
            docker compose down

            echo ">>> Building and starting containers"
            docker compose up --build -d

            echo ">>> Cleaning up old Docker images" 
            docker system prune -af --volumes
        env:
          PORT: 3020
          NODE_ENV: production
